# Generated by Django 6.0.5 on 2026-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_historicalauditevent'),
        ('referendums', '0003_alter_historicaloption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at'], 'verbose_name': "Esdeveniment d'auditoria", 'verbose_name_plural': "Esdeveniments d'auditoria"},
        ),
        migrations.AlterModelOptions(
            name='historicalauditevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': "historical Esdeveniment d'auditoria", 'verbose_name_plural': "historical Esdeveniments d'auditoria"},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('referendum_created', 'Referendum creat'), ('token_issued', 'Token emès'), ('vote_cast', 'Vot registrat'), ('results_viewed', 'Resultats consultats')], db_index=True, max_length=40, verbose_name='tipus'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadades'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='public_message',
            field=models.CharField(max_length=240, verbose_name='missatge públic'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='referendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='historicalauditevent',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='historicalauditevent',
            name='event_type',
            field=models.CharField(choices=[('referendum_created', 'Referendum creat'), ('token_issued', 'Token emès'), ('vote_cast', 'Vot registrat'), ('results_viewed', 'Resultats consultats')], db_index=True, max_length=40, verbose_name='tipus'),
        ),
        migrations.AlterField(
            model_name='historicalauditevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadades'),
        ),
        migrations.AlterField(
            model_name='historicalauditevent',
            name='public_message',
            field=models.CharField(max_length=240, verbose_name='missatge públic'),
        ),
        migrations.AlterField(
            model_name='historicalauditevent',
            name='referendum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.referendum', verbose_name='referèndum'),
        ),
    ]
