# Generated by Django 6.0.5 on 2026-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendums', '0003_alter_historicaloption_options_and_more'),
        ('votes', '0002_historicalvote_historicalvotertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vot', 'verbose_name_plural': 'historical Vots'},
        ),
        migrations.AlterModelOptions(
            name='historicalvotertoken',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Token de vot', 'verbose_name_plural': 'historical Tokens de vot'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vot', 'verbose_name_plural': 'Vots'},
        ),
        migrations.AlterModelOptions(
            name='votertoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'Token de vot', 'verbose_name_plural': 'Tokens de vot'},
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name="hash d'IP"),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='option',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.option', verbose_name='opció'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='receipt_code',
            field=models.CharField(db_index=True, max_length=64, verbose_name='codi de rebut'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='referendum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name="hash d'User-Agent"),
        ),
        migrations.AlterField(
            model_name='historicalvote',
            name='voter_token',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='votes.votertoken', verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='historicalvotertoken',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='historicalvotertoken',
            name='referendum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='historicalvotertoken',
            name='token_hash',
            field=models.CharField(max_length=128, verbose_name='hash del token'),
        ),
        migrations.AlterField(
            model_name='historicalvotertoken',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='utilitzat'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name="hash d'IP"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='referendums.option', verbose_name='opció'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='receipt_code',
            field=models.CharField(max_length=64, unique=True, verbose_name='codi de rebut'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='referendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_agent_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name="hash d'User-Agent"),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vote', to='votes.votertoken', verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='votertoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='votertoken',
            name='referendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='votertoken',
            name='token_hash',
            field=models.CharField(max_length=128, verbose_name='hash del token'),
        ),
        migrations.AlterField(
            model_name='votertoken',
            name='used_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='utilitzat'),
        ),
        migrations.AlterUniqueTogether(
            name='votertoken',
            unique_together={('referendum', 'token_hash')},
        ),
    ]
