# Generated by Django 6.0.5 on 2026-05-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referendums', '0002_historicaloption_historicalquestion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaloption',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Opció', 'verbose_name_plural': 'historical Opcions'},
        ),
        migrations.AlterModelOptions(
            name='historicalquestion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Pregunta', 'verbose_name_plural': 'historical Preguntes'},
        ),
        migrations.AlterModelOptions(
            name='historicalreferendum',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Referèndum', 'verbose_name_plural': 'historical Referèndums'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Opció', 'verbose_name_plural': 'Opcions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntes'},
        ),
        migrations.AlterModelOptions(
            name='referendum',
            options={'ordering': ['-created_at'], 'verbose_name': 'Referèndum', 'verbose_name_plural': 'Referèndums'},
        ),
        migrations.AlterField(
            model_name='historicaloption',
            name='label',
            field=models.CharField(max_length=80, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='historicaloption',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='historicaloption',
            name='question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.question', verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='referendum',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='historicalquestion',
            name='text',
            field=models.TextField(verbose_name='text de la pregunta'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripció'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False, verbose_name='és actiu'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='slug',
            field=models.SlugField(verbose_name='identificador únic'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inici'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='title',
            field=models.CharField(max_length=160, verbose_name='títol'),
        ),
        migrations.AlterField(
            model_name='historicalreferendum',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='actualitzat'),
        ),
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.CharField(max_length=80, verbose_name='etiqueta'),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='referendums.question', verbose_name='pregunta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='ordre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='referendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='referendums.referendum', verbose_name='referèndum'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='text de la pregunta'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creat'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripció'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False, verbose_name='és actiu'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='identificador únic'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='inici'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='title',
            field=models.CharField(max_length=160, verbose_name='títol'),
        ),
        migrations.AlterField(
            model_name='referendum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='actualitzat'),
        ),
    ]
